#!/usr/bin/env python

import argparse
import banner
import config
import importlib


args = argparse.ArgumentParser()
args.add_argument('--db', help = 'database URL', default = config.database)

subparsers = args.add_subparsers(dest = 'command')

init = subparsers.add_parser('init', help = 'initialize class database')

banner.setup_argparse(
        subparsers.add_parser('banner', help = 'interact directly with Banner'))

parse = subparsers.add_parser('parse', help = 'parse Banner class list')
parse.add_argument('file', nargs = '+', help = 'file containing class list')

args = args.parse_args()

# Set database URL and open the connection:
setattr(config, 'database', args.db)
import db

db.connect()

# Import and execute the named command:
importlib.import_module(args.command).run(args, db)

db.close()
