#!/usr/bin/env python3

import add
import argparse
import banner
import config
import group
import importlib
import logging
import mail
import parse
import passwd
import plot
import svn


args = argparse.ArgumentParser()
args.add_argument('--db', help = 'database URL', default = config.database)
args.add_argument('-v', '--verbose', help = 'log additional information',
                  action='store_true')

subparsers = args.add_subparsers(dest = 'command')

init = subparsers.add_parser('init', help = 'initialize class database')

add.setup_argparse(
        subparsers.add_parser('add', help = 'add student(s) manually'))

banner.setup_argparse(
        subparsers.add_parser('banner', help = 'interact directly with Banner'))

parsesub = subparsers.add_parser('parse', help = 'parse Banner HTML')
parse.setup_argparse(parsesub)

l = subparsers.add_parser('list', help = 'list students in the course')
importlib.import_module('list').setup_argparse(l)

l = subparsers.add_parser('transcript', help = 'show a student\'s transcript')
importlib.import_module('transcript').setup_argparse(l)

group.setup_argparse(subparsers.add_parser('group',
        help = 'group students together (e.g., for labs)'))

passwd.setup_argparse(subparsers.add_parser('passwd',
        help = "manage users' password hashes"))

svn.setup_argparse(
        subparsers.add_parser('svn', help = 'write SVN configuration'))

mail.setup_argparse(subparsers.add_parser('mail', help = 'send email to class'))

plotsub = subparsers.add_parser('plot', help = 'plot statistics')
plot.setup_argparse(plotsub)

args = args.parse_args()


logging.basicConfig(format='[%(levelname)s]\t%(message)s',
                    level=logging.DEBUG if args.verbose else logging.INFO)

# Set database URL and open the connection:
setattr(config, 'database', args.db)
import db

db.connect()

# Import and execute the named command:
importlib.import_module(args.command).run(args, db)

db.close()
