#!/usr/bin/env python

import argparse
import banner
import config
import importlib
import mail
import parse
import plot


args = argparse.ArgumentParser()
args.add_argument('--db', help = 'database URL', default = config.database)

subparsers = args.add_subparsers(dest = 'command')

init = subparsers.add_parser('init', help = 'initialize class database')

banner.setup_argparse(
        subparsers.add_parser('banner', help = 'interact directly with Banner'))

parsesub = subparsers.add_parser('parse', help = 'parse Banner HTML')
parse.setup_argparse(parsesub)

l = subparsers.add_parser('list', help = 'list students in the course')
importlib.import_module('list').setup_argparse(l)

mail.setup_argparse(subparsers.add_parser('mail', help = 'send email to class'))

plotsub = subparsers.add_parser('plot', help = 'plot statistics')
plot.setup_argparse(plotsub)

args = args.parse_args()

# Set database URL and open the connection:
setattr(config, 'database', args.db)
import db

db.connect()

# Import and execute the named command:
importlib.import_module(args.command).run(args, db)

db.close()
