#!/usr/bin/env python

import argparse
import json
import os
import sys

args = argparse.ArgumentParser()
args.add_argument('--prefix')
args.add_argument('--group-file', required = True)
args.add_argument('--user-suffix')
args.add_argument('directory', nargs = '+', help = 'directory names')
args = args.parse_args()

groups = json.load(open(args.group_file))

prefix = args.prefix
affected = set()


def email(username):
    if args.user_suffix is None:
        return username

    return username + args.user_suffix


for dirname in args.directory:
    if prefix:
        if not dirname.startswith(prefix):
            raise ValueError("Directory '%s' does not start with '%s'" % (
                    dirname, prefix
                ))

        dirname = dirname[len(prefix):]


    components = dirname.strip().split(os.sep)
    if len(components) < 2 or components[1] == '':
        continue

    (kind, name) = components[:2]

    if kind == 'groups':
        affected = affected.union(email(s) for s in groups[name])

    elif kind == 'students':
        affected.add(email(name))

    else:
        continue


print(','.join(affected))
