#!/usr/bin/env python

import argparse
import json
import os
import sys

args = argparse.ArgumentParser()
args.add_argument('--prefix')
args.add_argument('--group-file', required = True)
args.add_argument('filename', help = 'file (or -) with directory names')
args = args.parse_args()

input_file = sys.stdin if args.filename == '-' else open(args.filename, 'r')
groups = json.load(open(args.group_file))

prefix = args.prefix
affected = set()

for dirname in input_file:
    if prefix:
        if not dirname.startswith(prefix):
            raise ValueError, "Directory '%s' does not start with '%s'" % (
                    dirname, prefix
                )

        dirname = dirname[len(prefix):]


    components = dirname.split(os.sep)
    if len(components) < 2:
        continue

    (kind, name) = components[:2]

    if kind == 'groups':
        affected = affected.union(groups[components[1]])

    elif kind == 'students':
        affected.add(components[1])

    else:
        continue


print(','.join(affected))
